name: Code CI

on:
  push:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn --prefer-offline

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
